# Homework-2

## Part 1, Working with Numpy
    Your goal is to calculate the final grade for studnets in a class. 
      1. We have 10 Students in class, and 5 assessment score ( Homework, Project, Exam1, Exam2, Final Exam)for each
      student. Create a matrix containing grades of students, (rows are students, columns are assessments). Use for loop and input  function for entering the student name and grades. Enter arbitary grades from 0 to 100 for each assessment 
        2. Create a weigth vector containing weight of each assessment. Example (15%, 15%, 20%, 20%, 30% )
        3. Calculate the final grade for each students. Use Numpy to create your vector, matrix and calculating final grade.
        4. Convert final grades to letter format(90%-100% = A, 80%-89% = B, 70%-79% =C, 60%-69%=D and F for less than 60% )
        5. print out Student names and their grades

## Part 2, Working with Pandas

    - Step 1: Download the titanic.csv file from github.


    - Step 2: Read the file in Python and store it in a dataframe.


    - Step 3: Explore the data in your Jupyter notebook, eg. general info about data, some basic stats.
      Also print out the data for row index 100-105 and columns 'Name', 'Age', 'Fare'


    - Step 4: Create two dataframes, one containing data for only Categorical Variables and one for only Quantitative variable
  
    - Step 5: Write these newly created dataframe in .csv files.

In [3]:
import numpy as np
import random

names = ['Francis', 'Jack', 'Jacquelyn', 'Samuel', 'Esther', 'Leo', 'Catherine', 'Norris', 'Bruce', 'Anna']
grades = []
scores = np.zeros((10, 5))
assesments = ['homework', 'project' , 'exam 1', 'exam 2' , 'final']
for x in range(10):
    print(f"Enter 5 grades (0 to 100) for {names[x]} (student {x+1})")
    for y in range(5):
        grades = float(input(f"Enter their grade for the {assesments[y]}"))
        scores[x,y] = grades
weight = [0.15, 0.15, .20, .20, .30]
final = scores@weight
for z in range(len(final)):
    mark = final[z]

    if mark >= 90:
        print(f"{names[z]} received a grade of A")
    elif mark >= 80:
        print(f"{names[z]} received a grade of B")
    elif mark >= 70:
        print(f"{names[z]} received a grade of C")
    elif mark >= 60:
        print(f"{names[z]} received a grade of D")
    else:
        print(f"{names[z]} received a grade of F")

Enter 5 grades (0 to 100) for Francis (student 1)

Enter their grade for the homework 3
Enter their grade for the project 43
Enter their grade for the exam 1 34
Enter their grade for the exam 2 134
Enter their grade for the final 434

Enter 5 grades (0 to 100) for Jack (student 2)

Enter their grade for the homework 43
Enter their grade for the project 34
Enter their grade for the exam 1 34
Enter their grade for the exam 2 34
Enter their grade for the final 4

Enter 5 grades (0 to 100) for Jacquelyn (student 3)

Enter their grade for the homework 43
Enter their grade for the project 43
Enter their grade for the exam 1 4
Enter their grade for the exam 2 1
Enter their grade for the final 1

Enter 5 grades (0 to 100) for Samuel (student 4)

Enter their grade for the homework 1
Enter their grade for the project 1
Enter their grade for the exam 1 1
Enter their grade for the exam 2 1
Enter their grade for the final 1

Enter 5 grades (0 to 100) for Esther (student 5)

Enter their grade for the homework 1
Enter their grade for the project 1
Enter their grade for the exam 1 1
Enter their grade for the exam 2 1
Enter their grade for the final 1

Enter 5 grades (0 to 100) for Leo (student 6)

Enter their grade for the homework 1
Enter their grade for the project 1
Enter their grade for the exam 1 1
Enter their grade for the exam 2 1
Enter their grade for the final 1

Enter 5 grades (0 to 100) for Catherine (student 7)

Enter their grade for the homework 1
Enter their grade for the project 1
Enter their grade for the exam 1 1
Enter their grade for the exam 2 1
Enter their grade for the final 1

Enter 5 grades (0 to 100) for Norris (student 8)

Enter their grade for the homework 1
Enter their grade for the project 1
Enter their grade for the exam 1 1
Enter their grade for the exam 2 1
Enter their grade for the final 1

Enter 5 grades (0 to 100) for Bruce (student 9)

Enter their grade for the homework 1
Enter their grade for the project 1
Enter their grade for the exam 1 1
Enter their grade for the exam 2 1
Enter their grade for the final 1

Enter 5 grades (0 to 100) for Anna (student 10)

Enter their grade for the homework 1
Enter their grade for the project 1
Enter their grade for the exam 1 1
Enter their grade for the exam 2 1
Enter their grade for the final 1

Francis received a grade of A
Jack received a grade of F
Jacquelyn received a grade of F
Samuel received a grade of F
Esther received a grade of F
Leo received a grade of F
Catherine received a grade of F
Norris received a grade of F
Bruce received a grade of F
Anna received a grade of F

In [31]:
import pandas as pd
passengers = pd.read_csv('titanic.csv')
passengers.describe() # basic statistical info

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [32]:
passengers.loc[100:104, ['Name', 'Age', 'Fare']]

                                 Name   Age     Fare
100           Petranec, Miss. Matilda  28.0   7.8958
101  Petroff, Mr. Pastcho ("Pentcho")   NaN   7.8958
102         White, Mr. Richard Frasar  21.0  77.2875
103        Johansson, Mr. Gustaf Joel  33.0   8.6542
104    Gustafsson, Mr. Anders Vilhelm  37.0   7.9250

In [33]:
quantitative = passengers.select_dtypes(include=['category']) # only keep quantiative variables
categorical = passengers.select_dtypes(include=['int', 'float']) # only keep categorical variables
quantitative.to_csv('quantitative.csv', index=False)
categorical.to_csv('categorical.csv', index=False)